name: Dump Context
description: |
  Dump github contexts
runs:
  using: "composite" # this is key point
  steps:
    - name: Dump environment
      shell: bash
      run: |
        echo "::group::Export"
          export
        echo "::endgroup::"

        echo "::group::Dump github context"
          echo ${{ toJson(github) }}
        echo "::endgroup::"

        echo "::group::Dump job context"
          echo ${{ toJson(job) }}
        echo "::endgroup::"

        echo "::group::Dump runner context"
          echo ${{ toJson(runner) }}
        echo "::endgroup::"

        echo "::group::Dump strategy context"
          echo ${{ toJson(strategy) }}
        echo "::endgroup::"

        echo "::group::Dump matrix context"
          echo ${{ toJson(matrix) }}
        echo "::endgroup::"
