name: ban word checker
on:
  push:
    paths:
      - .github/workflows/*
      - .github/scripts/lint-banwords.sh
      - .github/ban-words.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash -eu .github/scripts/lint-banwords.sh --directory ".github/workflows" --file-filter "k8s.*yml" --definition "".github/ban-words.txt"
