name: ban word conftest
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test dev
        uses: YubicoLabs/action-conftest@v2
        with:
          files: ./.github/workflows/k8s_manifest_manual.yaml ./.github/workflows/k8s_manifest_pr.yaml ./.github/workflows/k8s_manifest_push.yaml
          policy: ./.github/workflows/policy/dev_env.rego
      - name: test staging
        uses: YubicoLabs/action-conftest@v2
        with:
          files: ./.github/workflows/k8s_manifest_manual.yaml ./.github/workflows/k8s_manifest_pr.yaml ./.github/workflows/k8s_manifest_push.yaml
          policy: ./.github/workflows/policy/staging_env.rego
        continue-on-error: true
