name: tag push only

on:
  push:
    tags:
      - "**" # only tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo not run on branch push
      - run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        id: CI_TAG
      - run: echo ${{ steps.CI_TAG.outputs.SOURCE_TAG }}
