name: build

on: [push]

jobs:
  dotnet-console:
    strategy:
      matrix:
        dotnet: ["3.1.201"] # support latest only
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      # build
      - run: dotnet build ./src/dotnet/console/ -c Debug
      # test
      - run: dotnet test ./src/dotnet/console-tests/ -c Debug
      # publish
      - run: dotnet publish ./src/dotnet/console/ -c Debug -o ./out/dotnet-console
      # upload
      - uses: actions/upload-artifact@v1
        with:
          name: dotnet-console
          path: ./out/dotnet-console

  dotnet-console-container:
    strategy:
      matrix:
        dotnet: ["3.1"] # support latest only
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      # build
      - run: dotnet build ./src/dotnet/console/ -c Debug
      # test
      - run: dotnet test ./src/dotnet/console-tests/ -c Debug
      # publish
      - run: dotnet publish ./src/dotnet/console/ -c Debug -o ./out/dotnet-console
      # upload
      - uses: actions/upload-artifact@v1
        with:
          name: dotnet-console
          path: ./out/dotnet-console
