name: cache
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Cache sha
        id: cache-sha
        uses: actions/cache@v2
        with:
          path: ~/cache
          key: ${{ runner.os }}-sha-${{ env.SHA }}

      - name: Generate sha
        if: steps.cache-sha.outputs.cache-hit != 'true'
        run: mkdir -p ~/cache && echo ${SHA} > ~/cache/.sha
      - run: cat ~/cache/.sha

      - name: public repo reference
        uses: actions/github-script@v3
        id: set-public-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.git.getRef({
              owner: context.repo.owner,
              repo: "githubactions-lab",
              ref: "heads/master"
            })
            console.log(result)
            return result.data.object.sha
      - run: echo "${{ steps.set-public-result.outputs.result }}"

      - name: private repo reference
        uses: actions/github-script@v3
        id: set-private-result
        with:
          github-token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }} # must be PAT
          script: |
            const result = await github.git.getRef({
              owner: context.repo.owner,
              repo: "testtest",
              ref: "heads/main"
            })
            console.log(result)
            return result.data.object.sha
      - run: echo "${{ steps.set-private-result.outputs.result }}"
