name: cancel redundant build
on: [push, pull_request]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      # no check for master and tag
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
