name: dotnet-test

# run on both branch push and tag push
on: [push]

jobs:
  dotnet-console:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test ./src/dotnet/console-tests/ -c Debug --logger GitHubActions
