name: dotnet-build

# run on both branch push and tag push
on: [push]

jobs:
  dotnet-console:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - run: ls -l $HOME/.dotnet
      - run: dotnet --version
      - run: dotnet --list-sdks
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: ls -l $HOME/.dotnet
      - run: dotnet --version
      - run: dotnet --list-sdks
      - run: dotnet build ./src/dotnet/console/ -c Debug
      - run: dotnet test ./src/dotnet/console-tests/ -c Debug
      - run: dotnet publish ./src/dotnet/console/ -c Debug -o ./out/dotnet-console
      - uses: actions/upload-artifact@v2
        with:
          name: dotnet-console
          path: ./out/dotnet-console

  dotnet-console-container:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:5.0
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build ./src/dotnet/console/ -c Debug
      - run: dotnet test ./src/dotnet/console-tests/ -c Debug
      - run: dotnet publish ./src/dotnet/console/ -c Debug -o ./out/dotnet-console-container
      - uses: actions/upload-artifact@v2
        with:
          name: dotnet-console-container
          path: ./out/dotnet-console-container

  ls:
    runs-on: ubuntu-latest
    needs:
      - dotnet-console
      - dotnet-console-container
    steps:
      - uses: actions/download-artifact@v2
      - run: ls -l
