name: if and env
on: push

jobs:
  env_reference:
    runs-on: ubuntu-latest
    env:
      APP: hoge
    steps:
      - run: echo "hoge"
        if: env.APP == 'hoge'
      - run: echo "fuga"
        if: env.APP == 'fuga'
