name: install tool
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p $HOME/local \
          && curl -Ls https://github.com/garethr/kubeval/releases/download/0.14.0/kubeval-linux-amd64.tar.gz -o $HOME/kubeval-linux-amd64.tar.gz \
          && tar -C $HOME/local/ -xzvf $HOME/kubeval-linux-amd64.tar.gz \
          && echo "::add-path::$HOME/local"
      - run: kubeval --version
