name: k8s manifest Push
on:
  push:
    branches:
      - master
jobs:
  push_manifest:
    env:
      REPO_MANIFEST: guitarrapc/kubernetes-manifest-lab
      MANIFEST_DIR: dev
      NAMESPACE_PREFIX: githubactions-sample-
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: ${{ env.REPO_MANIFEST }}
          path: ${{ env.REPO_MANIFEST }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "::set-env name=GIT_BRANCH::$(echo $REF | sed -e 's|refs/heads/||g')"
      - run: |
          mkdir -p ./${REPO_MANIFEST}/${MANIFEST_DIR}
          kubectl kustomize ./src/k8s/common/overlays/development \
            | sed -e "s|<namespace>|${NAMESPACE_PREFIX}${MANIFEST_DIR}|g" \
            | sed -e "s|<git-sha>|${{ github.sha }}|g" \
            | sed -e "s|<git-branch>|${GIT_BRANCH}}|g" \
            | sed -e "s|<git-link>|${{ github.event.commits.url }}|g" \
            | sed -e "s|<build-id>|${{ github.run_id }}|g" > ${REPO_MANIFEST}/${MANIFEST_DIR}/all.yaml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git status
          git add dev/*
          ret=$(git status| sed -ne 's|.*\(clean\)|\1|p')
          if [ -z $ret ];then
            git commit -m "(${MANIFEST_DIR}) update manifests ${REPO}/commit/${SHA} (${RUN_ID})" -m "compare: ${COMPARE_URL}"
          fi
        working-directory: ${{ env.REPO_MANIFEST }}
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SHA: ${{ github.sha }}
          COMPARE_URL: ${{ github.event.compare }}
      # todo: change to create pr.
      # uses: peter-evans/create-pull-request@v2
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          repository: ${{ env.REPO_MANIFEST }}
          branch: ${{ env.GIT_BRANCH }}
          directory: ${{ env.REPO_MANIFEST }}
