name: k8s manifest PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - src/k8s/**/*
      - .github/workflows/k8s*

jobs:
  push_manifest:
    env:
      REPO_MANIFEST: guitarrapc/kubernetes-manifest-lab
      MANIFEST_DIR: dev
      NAMESPACE_PREFIX: githubactions-sample-
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: ${{ env.REPO_MANIFEST }}
          path: ${{ env.REPO_MANIFEST }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "::set-env name=GIT_BRANCH::${{ github.head_ref }}"
      - run: |
          mkdir -p ./${REPO_MANIFEST}/${MANIFEST_DIR}
          kubectl kustomize ./src/k8s/common/overlays/development \
            | sed -e "s|<namespace>|${NAMESPACE_PREFIX}${MANIFEST_DIR}|g" \
            | sed -e "s|<git-sha>|${{ github.sha }}|g" \
            | sed -e "s|<git-branch>|${GIT_BRANCH}|g" \
            | sed -e "s|<git-link>|${{ github.event.pull_request.html_url }}|g" \
            | sed -e "s|<build-id>|${{ github.run_id }}|g" > ${REPO_MANIFEST}/${MANIFEST_DIR}/all.yaml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git status
          git add dev/*
          ret=$(git status| sed -ne 's|.*\(clean\)|\1|p')
          if [ -z $ret ];then
            git commit -m "(${MANIFEST_DIR}) update manifests ${REPO}#${LINK} (${RUN_ID})" -m "compare: ${COMPARE_URL}"
          fi
        working-directory: ${{ env.REPO_MANIFEST }}
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          LINK: ${{ github.event.pull_request.number }}
          SHA: ${{ github.sha }}
          COMPARE_URL: https://github.com/${{ github.repository }}/compare/master...${{ github.event.after }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          repository: ${{ env.REPO_MANIFEST }}
          branch: hoge
          directory: ${{ env.REPO_MANIFEST }}
