name: k8s manifest PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - src/k8s/**/*
      - .github/workflows/k8s*
  workflow_dispatch:
    inputs:
      branch:
        description: "branch name to clone"
        required: true
        default: "refs/head/master"
      manifest_dir:
        description: "manifest directory to push"
        required: true
        default: "dev"

jobs:
  push_manifest_manual:
    env:
      REPO_MANIFEST: guitarrapc/kubernetes-manifest-lab
      MANIFEST_DIR: dev
      NAMESPACE_PREFIX: githubactions-sample-
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_MANIFEST }}
          path: ${{ env.REPO_MANIFEST }}
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
      - run: echo "::set-env name=BRANCH::$(echo $REF | sed -e 's|refs/head/||')"
        env:
          REF: ${{ github.event.inputs.branch }}
      - run: |
          echo "::set-env name=GIT_BRANCH::$(echo $BRANCH | sed -e 's|/|-|g' -e 's/_/-/g')"
          echo "::set-env name=REMOTE_BRANCH::${REMOTE_BRANCH}"
          echo "::set-env name=SHA::$(git rev-parse HEAD)"
          echo "::set-env name=SHORT_SHA::$(git rev-parse --short HEAD)"
        env:
          REMOTE_BRANCH: ${{ github.event.repository.name }}/${{ env.BRANCH }}
      - run: |
          git fetch origin ${REMOTE_BRANCH}:${REMOTE_BRANCH} || git switch -C ${REMOTE_BRANCH}
          git reset --hard ${REMOTE_BRANCH}
        working-directory: ${{ env.REPO_MANIFEST }}
      - run: |
          mkdir -p ./${REPO_MANIFEST}/${MANIFEST_DIR}
          kubectl kustomize ./src/k8s/common/overlays/development \
            | sed -e "s|<namespace>|${NAMESPACE_PREFIX}${MANIFEST_DIR}|g" \
            | sed -e "s|<git-sha>|${SHA}|g" \
            | sed -e "s|<git-branch>|${GIT_BRANCH}|g" \
            | sed -e "s|<git-link>|${{ github.event.commits[0].url }}|g" \
            | sed -e "s|<build-id>|${{ github.run_id }}|g" > ${REPO_MANIFEST}/${MANIFEST_DIR}/all.yaml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git status
          git add "${MANIFEST_DIR}/*"
          ret=$(git status| sed -ne 's|.*\(clean\)|\1|p')
          if [ -z $ret ];then
            git commit -m "(${MANIFEST_DIR}) update manifests ${REPO}@${LINK} (${RUN_ID})" -m "compare: ${COMPARE_URL}"
          fi
        working-directory: ${{ env.REPO_MANIFEST }}
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          LINK: ${{ env.SHORT_SHA }}
          COMPARE_URL: https://github.com/${{ github.repository }}/compare/master...${{ env.SHORT_SHA }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          repository: ${{ env.REPO_MANIFEST }}
          branch: ${{ env.REMOTE_BRANCH }}
          directory: ${{ env.REPO_MANIFEST }}

  push_manifest:
    env:
      REPO_MANIFEST: guitarrapc/kubernetes-manifest-lab
      MANIFEST_DIR: dev
      NAMESPACE_PREFIX: githubactions-sample-
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_MANIFEST }}
          path: ${{ env.REPO_MANIFEST }}
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
      - run: echo "::set-env name=GIT_BRANCH::${REF}"
        env:
          REF: ${{ github.head_ref }}
      - run: echo "::set-env name=BRANCH::${BRANCH}"
        env:
          BRANCH: ${{ github.event.repository.name }}/${{ env.GIT_BRANCH }}
      - run: |
          git fetch origin ${BRANCH}:${BRANCH} || git switch -C ${BRANCH}
          git reset --hard ${BRANCH}
        working-directory: ${{ env.REPO_MANIFEST }}
      - run: |
          mkdir -p ./${REPO_MANIFEST}/${MANIFEST_DIR}
          kubectl kustomize ./src/k8s/common/overlays/development \
            | sed -e "s|<namespace>|${NAMESPACE_PREFIX}${MANIFEST_DIR}|g" \
            | sed -e "s|<git-sha>|${{ github.sha }}|g" \
            | sed -e "s|<git-branch>|${GIT_BRANCH}|g" \
            | sed -e "s|<git-link>|${{ github.event.pull_request.html_url }}|g" \
            | sed -e "s|<build-id>|${{ github.run_id }}|g" > ${REPO_MANIFEST}/${MANIFEST_DIR}/all.yaml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git status
          git add "${MANIFEST_DIR}/*"
          ret=$(git status| sed -ne 's|.*\(clean\)|\1|p')
          if [ -z $ret ];then
            git commit -m "(${MANIFEST_DIR}) update manifests ${REPO}#${LINK} (${RUN_ID})" -m "compare: ${COMPARE_URL}"
          fi
        working-directory: ${{ env.REPO_MANIFEST }}
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          LINK: ${{ github.event.pull_request.number }}
          SHA: ${{ github.sha }}
          COMPARE_URL: https://github.com/${{ github.repository }}/compare/master...${{ github.event.after }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          repository: ${{ env.REPO_MANIFEST }}
          branch: ${{ env.BRANCH }}
          directory: ${{ env.REPO_MANIFEST }}
