name: manual trigger
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
        required: false
      test_var:
        description: "A test variable"
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
      - run: echo ${INPUT_TEST_VAR}
      - run: export
      - run: |
          echo ::set-env name=INPUT_LOGLEVEL::${{ github.event.inputs.logLevel }}
          echo ::set-env name=INPUT_TAGS::${{ github.event.inputs.tags }}
      - run: |
          echo "Log level: ${INPUT_LOGLEVEL}"
          echo "Tags: ${INPUT_TAGS}"
