name: pr_label_get
on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
