name: pr_label_get
on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    runs-on: ubuntu-latest
    env:
      IS_HOGE: "false"
    steps:
      - run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
      - run: echo ::set-env name=IS_HOGE::${{ contains(github.event.pull_request.labels.*.name, 'hoge') }}
      - run: echo "${IS_HOGE}"
