name: push k8s manifest
on: [push, pull_request]
jobs:
  push_manifest:
    env:
      REPO_MANIFEST: kubernetes-manifest-lab
      MANIFEST_DIR: dev
      MANIFEST_BRANCH: mater
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_MANIFEST }}
          path: ${{ env.REPO_MANIFEST }}
          token: ${{ secrets.GitHub_PAT }}
      - run: |
          mkdir -p ./${REPO_MANIFEST}/${MANIFEST_DIR}
          kubectl kustomize ./src/k8s/common/overlays/development > ${REPO_MANIFEST}/${MANIFEST_DIR}/all.yaml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github actions bot"
          git commit -m "Add changes" -a
        working-directory: ${{ env.REPO_MANIFEST }}
      - uses: ad-m/github-push-action@master
        with:
          repository: kubernetes-manifest-lab
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.MANIFEST_BRANCH }}
          direcory: ${{ env.REPO_MANIFEST }}
