name: push k8s manifest
on: [pull_request]
jobs:
  push_manifest:
    env:
      REPO_MANIFEST: guitarrapc/kubernetes-manifest-lab
      MANIFEST_DIR: dev
      MANIFEST_BRANCH: master
      NAMESPACE_PREFIX: githubactions-sample-
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: ${{ env.REPO_MANIFEST }}
          path: ${{ env.REPO_MANIFEST }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -p ./${REPO_MANIFEST}/${MANIFEST_DIR}
          kubectl kustomize ./src/k8s/common/overlays/development \
            && sed -e "s|<namespace>|${NAMESPACE_PREFIX}-${MANIFEST_DIR}|g" \
            && sed -e "s|<git-sha>|${{ github.sha }}|g" \
            && sed -e "s|<git-branch>|${{ github.ref }}|g" \
            && sed -e "s|<git-link>|${{ github.event.pull_request.html_url }}|g" > ${REPO_MANIFEST}/${MANIFEST_DIR}/all.yaml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git status
          git add dev/*
          ret=$(git status| sed -ne 's|.*\(clean\)|\1|p')
          if [ -z $ret ];then
            git commit -m "(dev) update manifests ${REPO}#${PR_NUMBER}"
          fi
        working-directory: ${{ env.REPO_MANIFEST }}
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          repository: ${{ env.REPO_MANIFEST }}
          branch: ${{ env.MANIFEST_BRANCH }}
          directory: ${{ env.REPO_MANIFEST }}
