name: reuse local action
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use local action
        uses: ./.github/actions/local_composite_actions
        with:
          foo: BAR
