name: skip ci sample

on: ['push']

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - run: echo $COMMIT_MESSAGE
        env: 
          COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
