name: toc

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  toc:
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOC_TITLE: "Details"
          TOC_MAX_HEADER_LEVEL: "2"
          FOLDING: true
