name: trigger other repo
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               -d '{"ref": "${REF}"}' \
               ${URL}
        env:
          GIHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          URL: https://api.github.com/repos/guitarrapc/testtest/actions/workflows/test.yml/dispatches
          REF: main
