name: "Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create."
        required: true
      dry_run:
        description: "dry_run: true will never create commit/pr."
        required: true
        default: "false"

jobs:
  update-tag-release:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag }}
      TARGET_FILE: ./src/json/package.json
      CREATE_PR: ${{ github.event.inputs.create_pr }}
      DRY_RUN: ${{ github.event.inputs.dry_run }}
    steps:
      - uses: actions/checkout@v2
      - name: before
        run: cat ${{ env.TARGET_FILE}}
      - name: update package.json to version ${{ env.TAG }}
        run: sed -i -e "s/\(\"version\":\) \"\(.*\)\",/\1 \"${{ env.TAG }}\",/" ${{ env.TARGET_FILE }}
      - name: after
        run: cat ${{ env.TARGET_FILE}}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "feat: Update package.json to ${{ env.TAG }}" -a
          git tag ${{ env.TAG }}
          echo "NEW_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
        if: env.DRY_RUN == 'false'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }} # must use PAT to trigger other workflow
          branch: ${{ github.ref }}
          tags: true
        if: env.DRY_RUN == 'false'
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Ver.${{ env.TAG }}
          draft: "true"
          prerelease: "false"
